#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <QHostAddress>

enum {
    // 离线原因
    OFF_UNKNOWN,
    OFF_USER_LOGOUT,
    OFF_BIND_FAILED,
    OFF_CHALLENGE_FAILED,
	OFF_CHECK_MAC,
	OFF_SERVER_BUSY,
    OFF_WRONG_PASS,
    OFF_NOT_ENOUGH,
	OFF_FREEZE_UP,
	OFF_NOT_ON_THIS_IP,
	OFF_NOT_ON_THIS_MAC,
	OFF_TOO_MUCH_IP,
	OFF_UPDATE_CLIENT,
	OFF_NOT_ON_THIS_IP_MAC,
	OFF_MUST_USE_DHCP,
    OFF_TIMEOUT,
    OFF_DHCP_LOGIN_FAILED,

    // challenge 成功 获取到服务器返回的ip地址
    OBTAIN_IP_ADDRESS,

    // 当前状态
    STATE_OFFLINE,
    STATE_LOGGING,
    STATE_ONLINE

};

enum {
    LOGIN_CHECK_MAC          = 0x01,
    LOGIN_SERVER_BUSY        = 0x02,
    LOGIN_WRONG_PASS         = 0x03,
    LOGIN_NOT_ENOUGH         = 0x04,
    LOGIN_FREEZE_UP          = 0x05,
    LOGIN_NOT_ON_THIS_IP     = 0x07,
    LOGIN_NOT_ON_THIS_MAC    = 0x0B,
    LOGIN_TOO_MUCH_IP        = 0x14,
    LOGIN_UPDATE_CLIENT      = 0x15,
    LOGIN_NOT_ON_THIS_IP_MAC = 0x16,
    LOGIN_MUST_USE_DHCP      = 0x17
};

const int PORT_BIND=61440;
const int PORT_DEST=61440;
const QString SERVER_IP="10.100.61.3";

#endif // CONSTANTS_H
